# Generated by Django 3.1.1 on 2020-10-14 04:17

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scenarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SCENARIO_ID', models.IntegerField()),
                ('VERSION_ID', models.IntegerField()),
                ('NAME', models.CharField(max_length=1000)),
                ('PUBLIC', models.BooleanField(default=False)),
                ('NUM_CONVERSATIONS', models.IntegerField()),
                ('MATRIX', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=15), size=15)),
                ('CREATOR', models.IntegerField()),
                ('FIRST_PAGE', models.IntegerField()),
            ],
            options={
                'unique_together': {('SCENARIO_ID', 'VERSION_ID')},
            },
        ),
        migrations.CreateModel(
            name='pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PAGE_TYPE', models.CharField(max_length=1000)),
                ('PAGE_TITLE', models.CharField(max_length=1000)),
                ('NEXT_PAGE_ID', models.IntegerField()),
                ('PAGE_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pages1', to='tables.scenarios')),
                ('SCENARIO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages2', to='tables.scenarios')),
                ('VERSION_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages3', to='tables.scenarios')),
            ],
            options={
                'unique_together': {('PAGE_ID', 'SCENARIO', 'VERSION_ID')},
            },
        ),
        migrations.CreateModel(
            name='reflection_questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REFLECTION_QUESTION', models.TextField()),
                ('PAGE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_questions', to='tables.pages')),
            ],
            options={
                'unique_together': {('PAGE_ID', 'REFLECTION_QUESTION')},
            },
        ),
    ]
