# Generated by Django 3.1.1 on 2020-10-29 00:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('COURSE_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='professors',
            fields=[
                ('PROFESSOR_ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=1000)),
            ],
            options={
                'unique_together': {('PROFESSOR_ID', 'NAME')},
            },
        ),
        migrations.CreateModel(
            name='scenarios',
            fields=[
                ('SCENARIO_ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('VERSION_ID', models.IntegerField(default=0, editable=False)),
                ('NAME', models.CharField(max_length=1000)),
                ('SUB_TITLE', models.CharField(default=None, max_length=1000)),
                ('IS_FINISHED', models.BooleanField(default=False)),
                ('PUBLIC', models.BooleanField(default=False)),
                ('NUM_CONVERSATIONS', models.IntegerField(default=0)),
                ('FIRST_PAGE', models.IntegerField(default=1)),
                ('PROFESSOR_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios1', to='tables.professors')),
            ],
            options={
                'unique_together': {('SCENARIO_ID', 'VERSION_ID')},
            },
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('STUDENT_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='demographics',
            fields=[
                ('STUDENT_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='demographics', serialize=False, to='tables.students')),
                ('AGE', models.SmallIntegerField()),
                ('GRADE', models.CharField(choices=[('FR', 'FRESHMAN'), ('SO', 'SOPHOMORE'), ('JK', 'JUNIOR'), ('SE', 'SENIOR'), ('OT', 'OTHER')], max_length=2)),
                ('GENDER', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('OT', 'OTHER')], max_length=2)),
                ('RACE', models.CharField(max_length=50)),
                ('MAJOR', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='stakeholders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STAKEHOLDER_ID', models.IntegerField()),
                ('DESC', models.TextField()),
                ('MATRIX', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=15), size=15)),
                ('NAME', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders1', to='tables.scenarios')),
                ('SCENARIO_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders2', to='tables.scenarios')),
                ('VERSION_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders3', to='tables.scenarios')),
            ],
            options={
                'unique_together': {('STAKEHOLDER_ID', 'VERSION_ID')},
            },
        ),
        migrations.CreateModel(
            name='responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE', models.DateField()),
                ('CHOICE', models.TextField()),
                ('COURSE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses4', to='tables.courses')),
                ('E_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses2', to='tables.scenarios')),
                ('STUDENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses1', to='tables.students')),
                ('V_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses3', to='tables.scenarios')),
            ],
            options={
                'unique_together': {('STUDENT_ID', 'E_ID', 'V_ID', 'COURSE_ID')},
            },
        ),
        migrations.CreateModel(
            name='pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PAGE_ID', models.IntegerField()),
                ('PAGE_TYPE', models.CharField(choices=[('R', 'REFLECTION'), ('S', 'STAKEHOLDERS'), ('A', 'ACTION')], max_length=2)),
                ('PAGE_TITLE', models.CharField(max_length=1000)),
                ('PAGE_BODY', models.TextField(default=None)),
                ('NEXT_PAGE_ID', models.IntegerField()),
                ('SCENARIO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages1', to='tables.scenarios')),
                ('VERSION_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages2', to='tables.scenarios')),
            ],
            options={
                'unique_together': {('PAGE_ID', 'SCENARIO', 'VERSION_ID')},
            },
        ),
        migrations.CreateModel(
            name='conversations_had',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SCORE', models.IntegerField()),
                ('QUESTION', models.TextField()),
                ('COURSE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_had2', to='tables.responses')),
                ('DATE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_had4', to='tables.responses')),
                ('E_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_had3', to='tables.responses')),
                ('STAKEHOLDER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_had5', to='tables.stakeholders')),
                ('STUDENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_had1', to='tables.responses')),
            ],
        ),
        migrations.CreateModel(
            name='students_in',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COURSE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_in2', to='tables.courses')),
                ('STUDENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_in1', to='tables.students')),
            ],
            options={
                'unique_together': {('STUDENT_ID', 'COURSE_ID')},
            },
        ),
        migrations.CreateModel(
            name='stakeholder_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PAGE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder_page1', to='tables.pages')),
                ('STAKEHOLDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder_page2', to='tables.stakeholders')),
            ],
            options={
                'unique_together': {('PAGE_ID', 'STAKEHOLDER')},
            },
        ),
        migrations.CreateModel(
            name='stakeholder_in',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SCENARIO_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder2', to='tables.scenarios')),
                ('STAKEHOLDER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder1', to='tables.stakeholders')),
                ('VERSION_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder3', to='tables.scenarios')),
            ],
            options={
                'unique_together': {('STAKEHOLDER_ID', 'SCENARIO_ID', 'VERSION_ID')},
            },
        ),
        migrations.CreateModel(
            name='scenarios_for',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VERSION_ID', models.IntegerField()),
                ('COURSE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios_for2', to='tables.courses')),
                ('SCENARIO_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios_for1', to='tables.scenarios')),
            ],
            options={
                'unique_together': {('SCENARIO_ID', 'COURSE_ID', 'VERSION_ID')},
            },
        ),
        migrations.CreateModel(
            name='reflections_taken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REFLECTIONS', models.TextField()),
                ('COURSE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections_taken2', to='tables.responses')),
                ('DATE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections_taken4', to='tables.responses')),
                ('E_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections_taken3', to='tables.responses')),
                ('STUDENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections_taken1', to='tables.responses')),
            ],
            options={
                'unique_together': {('REFLECTIONS', 'STUDENT_ID', 'COURSE_ID', 'E_ID', 'DATE')},
            },
        ),
        migrations.CreateModel(
            name='reflection_questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REFLECTION_QUESTION', models.TextField()),
                ('PAGE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_questions1', to='tables.pages')),
            ],
            options={
                'unique_together': {('PAGE_ID', 'REFLECTION_QUESTION')},
            },
        ),
        migrations.CreateModel(
            name='professors_teach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COURSE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professors_teach2', to='tables.courses')),
                ('PROFESSOR_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professors_teach1', to='tables.professors')),
            ],
            options={
                'unique_together': {('PROFESSOR_ID', 'COURSE_ID')},
            },
        ),
        migrations.CreateModel(
            name='generic_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BODY', models.TextField()),
                ('PAGE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generic_page1', to='tables.pages')),
            ],
            options={
                'unique_together': {('PAGE_ID', 'BODY')},
            },
        ),
        migrations.CreateModel(
            name='conversations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QUESTION', models.TextField()),
                ('RESPONSE', models.TextField()),
                ('STAKEHOLDER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations1', to='tables.stakeholders')),
            ],
            options={
                'unique_together': {('STAKEHOLDER_ID', 'QUESTION', 'RESPONSE')},
            },
        ),
        migrations.CreateModel(
            name='choices_for',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CHOICES', models.TextField()),
                ('SCENARIO_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices_for1', to='tables.scenarios')),
                ('VERSION_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices_for2', to='tables.scenarios')),
            ],
            options={
                'unique_together': {('SCENARIO_ID', 'VERSION_ID', 'CHOICES')},
            },
        ),
    ]
