# Generated by Django 3.1.2 on 2020-12-02 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='responses',
            unique_together={('STUDENT', 'SCENARIO', 'VERSION', 'COURSE', 'ACTION_PAGE')},
        ),
    ]
