# Generated by Django 3.1.1 on 2020-12-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversations',
            name='QUESTION',
            field=models.TextField(default='default'),
        ),
        migrations.AlterField(
            model_name='conversations',
            name='RESPONSE',
            field=models.TextField(default='default'),
        ),
        migrations.AlterField(
            model_name='stakeholders',
            name='DESCRIPTION',
            field=models.TextField(default='default'),
        ),
        migrations.AlterField(
            model_name='stakeholders',
            name='INTRODUCTION',
            field=models.TextField(default='default'),
        ),
        migrations.AlterField(
            model_name='stakeholders',
            name='JOB',
            field=models.TextField(default='default'),
        ),
        migrations.AlterField(
            model_name='stakeholders',
            name='NAME',
            field=models.CharField(default='deafult', max_length=1000),
        ),
    ]
