# Generated by Django 3.1.1 on 2020-10-14 06:08

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_page',
            fields=[
                ('PAGE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='event_pages', serialize=False, to='tables.pages')),
                ('BODY', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='stakeholders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STAKEHOLDER_ID', models.IntegerField()),
                ('DESC', models.TextField()),
                ('MATRIX', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=15), size=15)),
                ('SCENARIO_ID', models.IntegerField()),
                ('NAME', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders1', to='tables.scenarios')),
                ('VERSION_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders2', to='tables.scenarios')),
            ],
            options={
                'unique_together': {('STAKEHOLDER_ID', 'VERSION_ID')},
            },
        ),
        migrations.CreateModel(
            name='stakeholder_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PAGE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder_pages', to='tables.pages')),
                ('STAKEHOLDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder_pages', to='tables.stakeholders')),
            ],
            options={
                'unique_together': {('PAGE_ID', 'STAKEHOLDER')},
            },
        ),
        migrations.CreateModel(
            name='stakeholder_in',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SCENARIO_ID', models.IntegerField()),
                ('STAKEHOLDER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder_in1', to='tables.stakeholders')),
                ('VERSION_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder_in2', to='tables.scenarios')),
            ],
            options={
                'unique_together': {('STAKEHOLDER_ID', 'SCENARIO_ID', 'VERSION_ID')},
            },
        ),
        migrations.CreateModel(
            name='choices_for',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SCENARIO_ID', models.IntegerField()),
                ('CHOICES', models.TextField()),
                ('VERSION_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices_for', to='tables.scenarios')),
            ],
            options={
                'unique_together': {('SCENARIO_ID', 'VERSION_ID', 'CHOICES')},
            },
        ),
    ]
