# Generated by Django 3.1.1 on 2020-10-14 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_choices_for_event_page_stakeholder_in_stakeholder_page_stakeholders'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('COURSE_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='professors',
            fields=[
                ('PROFESSOR_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=1000)),
            ],
            options={
                'unique_together': {('PROFESSOR_ID', 'NAME')},
            },
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('STUDENT_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='dempgraphics',
            fields=[
                ('STUDENT_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='demographics', serialize=False, to='tables.students')),
                ('AGE', models.SmallIntegerField()),
                ('GRADE', models.CharField(choices=[('FR', 'FRESHMAN'), ('SO', 'SOPHOMORE'), ('JK', 'JUNIOR'), ('SE', 'SENIOR'), ('OT', 'OTHER')], max_length=2)),
                ('GENDER', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('OT', 'OTHER')], max_length=2)),
                ('RACE', models.CharField(max_length=50)),
                ('MAJOR', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE', models.DateField()),
                ('CHOICE', models.TextField()),
                ('COURSE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses4', to='tables.courses')),
                ('E_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses2', to='tables.scenarios')),
                ('STUDENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses1', to='tables.students')),
                ('V_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses3', to='tables.scenarios')),
            ],
            options={
                'unique_together': {('STUDENT_ID', 'E_ID', 'V_ID', 'COURSE_ID')},
            },
        ),
        migrations.CreateModel(
            name='conversations_had',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SCORE', models.IntegerField()),
                ('QUESTION', models.TextField()),
                ('COURSE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_had2', to='tables.responses')),
                ('DATE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_had4', to='tables.responses')),
                ('E_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_had3', to='tables.responses')),
                ('STAKEHOLDER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_had5', to='tables.stakeholders')),
                ('STUDENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_had1', to='tables.responses')),
            ],
        ),
        migrations.AlterField(
            model_name='scenarios',
            name='CREATOR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='tables.professors'),
        ),
        migrations.CreateModel(
            name='students_in',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COURSE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_in2', to='tables.courses')),
                ('STUDENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_in1', to='tables.students')),
            ],
            options={
                'unique_together': {('STUDENT_ID', 'COURSE_ID')},
            },
        ),
        migrations.CreateModel(
            name='scenarios_for',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SCENARIO_ID', models.IntegerField()),
                ('VERSION_ID', models.IntegerField()),
                ('COURSE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios_for', to='tables.courses')),
            ],
            options={
                'unique_together': {('SCENARIO_ID', 'COURSE_ID', 'VERSION_ID')},
            },
        ),
        migrations.CreateModel(
            name='reflections_taken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REFLECTIONS', models.TextField()),
                ('COURSE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_taken2', to='tables.responses')),
                ('DATE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_taken4', to='tables.responses')),
                ('E_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_taken3', to='tables.responses')),
                ('STUDENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_taken1', to='tables.responses')),
            ],
            options={
                'unique_together': {('REFLECTIONS', 'STUDENT_ID', 'COURSE_ID', 'E_ID', 'DATE')},
            },
        ),
        migrations.CreateModel(
            name='professors_teach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COURSE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professors_teach1', to='tables.courses')),
                ('PROFESSOR_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professors_teach1', to='tables.professors')),
            ],
            options={
                'unique_together': {('PROFESSOR_ID', 'COURSE_ID')},
            },
        ),
        migrations.CreateModel(
            name='conversations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QUESTION', models.TextField()),
                ('RESPONSE', models.TextField()),
                ('STAKEHOLDER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='tables.stakeholders')),
            ],
            options={
                'unique_together': {('STAKEHOLDER_ID', 'QUESTION', 'RESPONSE')},
            },
        ),
    ]
