# Generated by Django 3.1.1 on 2020-11-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20201116_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action_page',
            name='RESULT_PAGE',
            field=models.IntegerField(null=True),
        ),
    ]
