# Generated by Django 3.1.1 on 2020-12-02 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20201202_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reflections_taken',
            old_name='PAGE',
            new_name='REFLECTION_PAGE',
        ),
        migrations.AlterField(
            model_name='conversations_had',
            name='CONVERSATION',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_had7', to='tables.conversations'),
        ),
        migrations.AlterUniqueTogether(
            name='responses',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='actions_taken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ACTION_PAGE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_taken2', to='tables.action_page')),
                ('RESPONSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_taken1', to='tables.responses')),
            ],
        ),
        migrations.RemoveField(
            model_name='responses',
            name='ACTION_PAGE',
        ),
        migrations.RemoveField(
            model_name='responses',
            name='CHOICE',
        ),
    ]
