# Generated by Django 3.1.2 on 2020-12-02 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20201202_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflections_taken',
            name='PAGE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reflections_taken6', to='tables.reflection_questions'),
        ),
    ]
