# Generated by Django 3.1.1 on 2020-11-16 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_auto_20201116_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='NEXT_PAGE',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages3', to='tables.pages'),
        ),
    ]
