# Generated by Django 3.1.1 on 2020-10-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_auto_20201014_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarios',
            name='IS_FINISHED',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scenarios',
            name='SUB_TITLE',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
