# Generated by Django 2.2.12 on 2020-12-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_auto_20201202_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholders',
            name='NAME',
            field=models.CharField(default='default', max_length=1000),
        ),
    ]
