# Generated by Django 3.1.2 on 2020-12-02 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_reflections_taken_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reflections_taken',
            name='PAGE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reflections_taken6', to='tables.pages'),
        ),
    ]
