# Generated by Django 3.1.1 on 2020-10-15 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_auto_20201014_1621'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dempgraphics',
            new_name='demographics',
        ),
    ]
