# Generated by Django 3.1.1 on 2020-10-20 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_auto_20201020_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='PAGE_ID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scenarios',
            name='FIRST_PAGE',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios1', to='tables.pages'),
        ),
    ]
