# Generated by Django 3.1.1 on 2020-10-15 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_auto_20201015_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographics',
            name='STUDENT_ID',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='demographics', serialize=False, to='tables.students'),
        ),
    ]
