# Generated by Django 3.1.1 on 2020-11-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_auto_20201117_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigned_to',
            name='VERSION',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='conversations_had',
            name='VERSION',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='issues',
            name='VERSION',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='pages',
            name='VERSION',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='reflections_taken',
            name='VERSION',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='responses',
            name='VERSION',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='scenarios_for',
            name='VERSION',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='stakeholders',
            name='VERSION',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='student_times',
            name='VERSION',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
