# Generated by Django 3.1.2 on 2020-11-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_auto_20201117_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='PAGE_BODY',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
