# Generated by Django 3.1.1 on 2020-10-20 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_auto_20201020_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenarios',
            name='FIRST_PAGE',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scenarios1', to='tables.pages'),
        ),
    ]
