# Generated by Django 3.1.1 on 2020-10-20 20:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_auto_20201020_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenarios',
            name='MATRIX',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=None, size=15), default=None, size=15),
        ),
    ]
