# Generated by Django 3.1.2 on 2020-11-19 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_pages_page_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversations_had',
            name='STUDENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_had1', to='tables.students'),
        ),
        migrations.AlterField(
            model_name='reflections_taken',
            name='STUDENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections_taken1', to='tables.students'),
        ),
    ]
