# Generated by Django 3.1.1 on 2020-10-20 20:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_auto_20201020_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenarios',
            name='MATRIX',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=15), size=15),
        ),
    ]
