# Generated by Django 3.1.1 on 2020-11-20 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_auto_20201119_0025'),
        ('tables', '0006_pages_page_body'),
    ]

    operations = [
    ]
