# Generated by Django 3.1.2 on 2020-12-02 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_auto_20201119_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigned_to',
            name='VERSION',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='conversations_had',
            name='VERSION',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='issues',
            name='VERSION',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='pages',
            name='NEXT_PAGE',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='VERSION',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='reflections_taken',
            name='VERSION',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='responses',
            name='VERSION',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='scenarios',
            name='PROFESSOR',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scenario_creator2', to='tables.professors'),
        ),
        migrations.AlterField(
            model_name='scenarios_for',
            name='VERSION',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='stakeholders',
            name='VERSION',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='student_times',
            name='VERSION',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
