# Generated by Django 3.1.2 on 2020-12-02 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0008_auto_20201202_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversations_had',
            name='SCENARIO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_had3', to='tables.scenarios'),
        ),
        migrations.AlterField(
            model_name='reflections_taken',
            name='SCENARIO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections_taken3', to='tables.scenarios'),
        ),
    ]
