# Generated by Django 3.1.1 on 2020-10-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0008_auto_20201020_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenarios',
            name='FIRST_PAGE',
            field=models.IntegerField(default=1),
        ),
    ]
