# Generated by Django 3.1.1 on 2020-12-01 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0009_auto_20201128_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenarios',
            name='PROFESSOR',
        ),
        migrations.CreateModel(
            name='scenario_creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROFESSOR', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scenario_creator2', to='tables.professors')),
                ('SCENARIO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_creator1', to='tables.scenarios')),
            ],
        ),
    ]
