# Generated by Django 3.1.1 on 2020-10-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0009_auto_20201020_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='PAGE_BODY',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='pages',
            name='PAGE_TYPE',
            field=models.CharField(choices=[('R', 'REFLECTION'), ('S', 'STAKEHOLDERS'), ('A', 'ACTION')], max_length=2),
        ),
    ]
