# Generated by Django 3.1.2 on 2020-12-02 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0010_auto_20201201_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarios',
            name='PROFESSOR',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scenario_creator2', to='tables.professors'),
        ),
        migrations.DeleteModel(
            name='scenario_creator',
        ),
    ]
