# Generated by Django 3.1.2 on 2020-10-21 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0010_auto_20201021_1812'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dempgraphics',
            new_name='demographics',
        ),
    ]
