# Generated by Django 3.1.2 on 2020-10-21 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0011_auto_20201021_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_page',
            name='PAGE_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='event_page', serialize=False, to='tables.pages'),
        ),
    ]
