# Generated by Django 3.1.1 on 2020-09-29 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='scneario_name',
            new_name='scenario_name',
        ),
    ]
