# Generated by Django 3.1.1 on 2020-10-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200929_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='conclusion',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
