# Generated by Django 3.1.1 on 2020-10-15 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201013_0250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
